### ISSUE TITLE
Why not use forEach/map?

### ISSUE THREAD

**Issue by Mokerstier** [mbergevoet/web-app-from-scratch-2021#7]
https://github.com/mbergevoet/web-app-from-scratch-2021/blob/d42399c867cee002dbaae25a3de00e4e3f75c237/scripts/display.js#L6-L15

Ik denk dat het mooier is om hier een forEach te gebruiken

```
data.forEach((movie) => {
   // en dan hier je elementen maken
})
```

op die manier voorkom je ook dat je `data[i]` hoeft te gebruiken
je code wordt dan **NOG** overzichtelijker!

lekker bezig voor de rest!

**Comment by mbergevoet** [comment]
Ik heb de forEach nu geimplementeerd. Dank voor je feedback!
